---
title: "The Grammar of Graphics for Creating Graphs"
author:
  name: "Carsten Lange"
  email: "clange@cpp.edu"
  affiliation: "Cal Poly, Pomona"

format: 
  live-revealjs:
    theme: [moon, CustomCL.scss]
    smaller: true
    controls: true
    chalkboard:
      theme: whiteboard
      boardmarker-width: 2.7
    incremental: false
    scrollable: true
    footer: "<a href='https://ggplot2-book.org/getting-started.html'>Textbook </a> "
  
webr:
  packages:
    - tidyverse
    - ggplot2
    - rio
    - palmerpenguins
    - TeachHist

engine: knitr 

execute:
  daemon: false
  warning: false
  message: false
---

{{< include ./_extensions/r-wasm/live/_knitr.qmd >}}

## Generating Data

Below are  observation from an AB-Test. A companies web users were randomly routed to 

1) the traditional webpage (`Control`) 
2) An audio enhanced webpage (`Audio`) 
3) A video  enhanced webpage (`Video`).

For several days $Conversions$, $Purchases$ and $Revenue$ were measured for ech of the three *Treatments* (`Control`, `Audio`), and `Video`.

The data (artificially created from the [Palmer Penguin Dataset](https://allisonhorst.github.io/palmerpenguins/articles/intro.html){target="_blank"}) are shown below:

```{webr}
#| autorun: true
#| echo: false

DataWebPurch=penguins |> 
       select(Conversions=flipper_length_mm, Treatment=species,
              Purchases=bill_depth_mm, 
              Revenue=bill_length_mm) |> 
              drop_na() |> 
              mutate(Purchases=round(Purchases),
                     Revenue=Revenue*100) |> 
              select(Treatment, everything())
              
levels(DataWebPurch$Treatment)=c("Control", "Audio", "Video")
set.seed(111)
kable(slice_sample(DataWebPurch, n=600))
```

## Grammar of Graphics



1. **Data and Aesthetics (Visuals)**  
   Mappings  between data variables and visual properties. E.g., `x`, `y`, `color`, `size`, `shape`  
   (assigning data to *Aesthetics*)



3. **Geoms (Geometric Objects)**  
   The shapes drawn (points, lines, bars, boxplots...).  
   
4. **Scales**  
   Rules that translate data values into visual values  
   (numbers → positions, categories/numbers → colors or color scales, etc.).  
9. **Annotations**  
   Extra information layered on top of the plot.  
   - Titles, subtitles, captions (`labs(title = ...)`)  
   - Labels, reference lines (`geom_text()`, `geom_hline()`)  
   - Custom notes
   
5. **Stats (statistical transformations)**  
   Optional transformations applied before drawing geoms.  
   - Example: `geom_histogram()` uses `stat_bin()` to compute counts.  
   - Example: `geom_smooth()` uses `stat_smooth()` to fit a regression line.
   
  

6. **Coordinates (coordinate systems)**  
   How the plot space is drawn.  
   - Cartesian (default), polar (`coord_polar()`), flipped (`coord_flip()`), maps, etc.  

7. **Facets**  (Trick to add another dimension)
   Splitting data into multiple small plots (e.g., `facet_wrap(~gender)`).  

8. **Themes**  
   Non–data elements: fonts, grid lines, background, legend placement, axis styling.  



##  Step 1: Mapping Variables to Aestetics: ggplot(){.smaller}

Aesthetics: Are the visual elements of a diagram

At this stage, you are just saying: “this data column is assigned (mapped) to  this visual property.”

```{webr}
ggplot(DataWebPurch, mapping = aes(x=Purchases, y=Revenue))
```

##  Step 2: Choosing Geometric Objects: geom_xxx()

Examples:

- geom_point() → draws points (scatter plots)
- geom_line() → draws lines (time series, trends)
- geom_bar() → draws bars (histograms, bar charts) based on counts
- geom_col() → draws bars  based on (continues) variables)
- geom_smooth → draws a smooth line representation of point data
- geom_histogram() → draws histogram bins
- geom_boxplot() → draws box-and-whisker plots

##  Step 2: Choosing Geometric Objects: geom_point()


```{webr}
ggplot(DataWebPurch, mapping = aes(x=Purchases, y=Revenue))+
  geom_point()
```

##  Step 2: Choosing Geometric Objects: geom_point(color="red")

```{webr}
ggplot(DataWebPurch, mapping = aes(x=Purchases, y=Revenue))+
  geom_point(color="red", size=5, shape = "*")
```


## Back to Step 1: Adding additional Data to Aesteics (3 Dimension)

```{webr}
ggplot(DataWebPurch, mapping = aes(x=Purchases, y=Revenue, color=Treatment))+
  geom_point()
```
## Back to Step 2: Adding Another GEOM (3 trend lines)

```{webr}
#| message: false
#| warning: false
ggplot(DataWebPurch, aes(x=Purchases, y=Revenue, color = Treatment)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)
```



## Back to Step 2: Adding Another GEOM? Solution 1  (1 trend line)

```{webr}
#| warning: false
#| message: false
ggplot(DataWebPurch, aes(Purchases, Revenue, color = Treatment)) +
geom_point() +
geom_smooth(aes(x=Purchases, y=Revenue),
              method = "lm", se = FALSE,
              inherit.aes = FALSE) # possibly adding , color = "black"
```

## Back to Step 2: Adding Another GEOM? Solution 2  (1 trend lines)

```{webr}
#| warning: false
#| message: false
ggplot(DataWebPurch, aes(Purchases, Revenue, color = Treatment)) +
geom_point() +
geom_smooth(method = "lm", se = FALSE, color = "black")
```



## Back to Step 2: Adding Two GEOMs? Cool Solution (1 +3 trend lines; Simpson’s Paradox)

```{webr}
#| warning: false
#| message: false
ggplot(DataWebPurch, mapping=aes(x=Purchases, y=Revenue)) +
geom_point(mapping=aes(color = Treatment)) +
geom_smooth(method = "lm", se = FALSE, color="black") +
geom_smooth(aes(color = Treatment), method = "lm", se = FALSE)
```

## Back to Step 2: Adding too Many GEOMs? --- Convoluted

```{webr}
#| warning: false
#| message: false
DataMeans=DataWebPurch %>%
    group_by(Treatment) %>%
    summarise(RevMean = mean(Revenue),
              PurchMean=mean(Purchases))

ggplot(DataWebPurch, mapping=aes(x=Purchases, y=Revenue)) +
geom_point(mapping=aes(color = Treatment)) +
geom_smooth(method = "lm", se = FALSE, color="black") +
geom_smooth(aes(color = Treatment), method = "lm", se = FALSE)+
  geom_vline(xintercept = DataMeans$PurchMean[1],              color="red")+
  geom_vline(xintercept = DataMeans$PurchMean[2],              color="green")+
  geom_vline(xintercept = DataMeans$PurchMean[3],              color="blue")+
  geom_hline(yintercept = DataMeans$RevMean[1],              color="red")+
  geom_hline(yintercept = DataMeans$RevMean[2],              color="green")+
  geom_hline(yintercept = DataMeans$RevMean[3],              color="blue")
```

## Step 3: Scaling `x`-axis and `y`-axis (see next slide)

```{webr}
#| warning: false
#| message: false
ggplot(DataWebPurch, mapping=aes(x=Purchases, y=Revenue)) +
geom_point(mapping=aes(color = Treatment)) +
geom_smooth(aes(color = Treatment), method = "lm", se = FALSE)
```

## Step 3: Scaling `x`-axis and `y`-axis 

```{webr}
#| warning: false
#| message: false
ggplot(DataWebPurch, mapping=aes(x=Purchases, y=Revenue)) +
geom_point(mapping=aes(color = Treatment)) +
geom_smooth(aes(color = Treatment), method = "lm", se = FALSE)+
scale_x_continuous(limits = c(12,24), breaks = seq(12,24,1), 
                   minor_breaks = seq(12,24,1) )+
scale_y_continuous(limits = c(3000,6000), breaks = seq(3000,6000,500), 
                   minor_breaks = seq(3000,6000,250) )

```

## Step 4: Adding Labels with `lab()`

```{webr}
#| warning: false
#| message: false
ggplot(DataWebPurch, mapping=aes(x=Purchases, y=Revenue)) +
geom_point(mapping=aes(color = Treatment)) +
geom_smooth(mapping=aes(color = Treatment), method = "lm", se = FALSE)+
scale_x_continuous(limits = c(12,24), breaks = seq(12,24,1), 
                   minor_breaks = seq(12,24,1) )+
scale_y_continuous(limits = c(3000,6000), breaks = seq(3000,6000,500), 
                   minor_breaks = seq(3000,6000,250) )+
labs(
  title = "Differnt Web Designs",
  subtitle = "Daily Data, 2026",
  caption = "Palmer Penguins",
  x = "Purchases per Day",
  y = "Revenue in US$"
)
```

## Bar Chart and Column Chart

These charts have a categorical variable as the x-axis possibly encoded as a `factor`.

- A Bar chart has counts (or count related), pseudo-continuous  y-axis

- A Col chart displays predetermined continuous variable on the y-axis

## Bar Chart

```{webr}
ggplot(DataWebPurch, mapping=aes(x=Treatment, fill=Treatment))+
geom_bar()+
scale_fill_viridis_d(option="magma")
```

## Col Chart (with Assessible Colors)

```{webr}
# Summarize by Treatment
DataWebPurchMeans <- DataWebPurch |> 
  group_by(Treatment) |> 
  summarise(
    MeanRevenue = mean(Revenue)
  )
kable(DataWebPurchMeans)
```

## Plot MeanRevenue by Treatment
```{webr}
ggplot(DataWebPurchMeans, aes(x = Treatment, y = MeanRevenue, fill = Treatment)) +
  geom_col() +
  scale_fill_manual(values = c("red","green","blue")) +
  labs(
    title = "Mean Revenue by Treatment",
    x = "Treatment",
    y = "Mean Revenue"
  )


```

## Histogram ggplot

```{webr}
#| warning: false
#| message: false
ggplot(DataWebPurch, aes(x = Revenue)) +
  geom_histogram(binwidth = 300, fill="red", color="black")+
  scale_x_continuous(limits = c(3000,6300), breaks = seq(3000,6000,300), 
                     minor_breaks = seq(3000,6300,100) )
```

## Time Series for Apple Stock

```{webr}
DataStockTimeSeries=
  data.frame(EndOfYear=seq(2019,2023,1), 
             Price=c(71.25,129.90,174.91,128.72,191.8))
library(ggthemes)
ggplot(DataStockTimeSeries, mapping=aes(x=EndOfYear, y=Price))+
  geom_line(color="red", linewidth=2 )+
  labs(title="Apple Stock Price",
       subtitle="(end of year)",
       x="Year")+
  theme_economist()
```


## More about Ggplot2

Thomas Lin Pedersen

[ggplot workshop part 1 (2,5 hours)](https://www.youtube.com/watch?v=h29g21z0a68){target="_blank"}




## Histogram-Count with `TeachHistCount`  {.smaller}
### (ggplot is under the hood)

```{webr}
#| autorun: true
#| echo: false
cat("Mean Revenue:", mean(DataWebPurch$Revenue), "StdDev:", sd(DataWebPurch$Revenue),"Total Count:", nrow(DataWebPurch))
```

```{webr}
#| warning: false
#| message: false
TeachHistCounts(PlotData=DataWebPurch["Revenue"], VLine1=4938, PrintZAxis = FALSE)
```

## Histogram - Relative Frequencies with `TeachHistRelFreq` {.smaller}
```{webr}
#| autorun: true
#| echo: false
cat("Mean Revenue:", mean(DataWebPurch$Revenue), "StdDev:", sd(DataWebPurch$Revenue),"Total Count:", nrow(DataWebPurch))
```

$RelFreq=\frac{Count}{TotalCount}$. Example (left of mean): $\frac{98}{342}=0.28655$

```{webr}
#| warning: false
#| message: false
TeachHistRelFreq(PlotData=DataWebPurch["Revenue"],  VLine1=4938, PrintZAxis = FALSE)
```

## Histogram - Densities with `TeachHistDens`  {.smaller}
```{webr}
#| autorun: true
#| echo: false
cat("Mean Revenue:", mean(DataWebPurch$Revenue), "StdDev:", sd(DataWebPurch$Revenue),"Total Count:", nrow(DataWebPurch))
```
$Density=\frac{RelFreq}{StdDev}$. Example (left of mean): $\frac{0.28655}{545.9584}=0.0005248568$

**Density is not easy to predict**, but **RelFreq** is now depicted as the **area of each bar** (proof next slide)

```{webr}
#| warning: false
#| message: false
TeachHistDens(PlotData=DataWebPurch["Revenue"], VLine1=4938, PrintZAxis = FALSE)
```

## Histogram - Densities with TeachHistDens
$Density=\frac{RelFreq}{StdDev}$. Example (left of mean): $\frac{0.28655}{545.9584}=0.0005248568$
$$AreaOfBar=StdDev\cdot \frac{RelFreq}{StdDev}=RelFreq$$


**Example (left of mean):** $=0.0005248568\cdot 545.9584 = 0.2865$

```{webr}
#| warning: false
#| message: false
library(plotly)
ggplotly(
TeachHistDens(PlotData=DataWebPurch["Revenue"], VLine1=4938, PrintZAxis = FALSE)
  )
```


