---
title: "Introduction"
author:
  name: "Carsten Lange"
  email: "clange@cpp.edu"
  affiliation: "Cal Poly, Pomona"

format: 
  revealjs:
    echo: true
    code-fold: true
    output-location: fragment
    incremental: false
    warning: false
    message: false
    navigation-mode: vertical
    scrollable: true
    smaller: true
    footer: '<a href="https://r4ds.hadley.nz/data-transform.html#groups" target="_blank">Read Textbook</a>'
  
    
include-in-header:
  text: |
    <style>
    .reveal .slides section:not(:first-of-type) h1,
    .reveal .slides section:not(:first-of-type) h2,
    .reveal .slides section:not(:first-of-type) h3,
    .reveal .slides section:not(:first-of-type) h4,
    .reveal .slides section:not(:first-of-type) h5,
    .reveal .slides section:not(:first-of-type) h6 {
      font-size: 142% !important;
    }
    </style>
    
---

## Success in The Course

::: incremental
- Use AI responsible
- Read the textbook
- Follow the Learning Guide!!!
- Read read the syllabus
:::

## Course Content

::: incremental

- Basic Statistics Concept
- Data Engineering with R
- Data Visualization
- Data reporting with Quarto
  - Writing Paper
  - Developing Power Point Slides

:::

## Why R?

::: incremental

- Excel analytics is not reproducible
- SPSS focuses on surveys
- STATA and SAS are commercial products
  - not free
  - progress has to go through the corporate hierachie and therefore is slower
  - limited support community

:::

## R and/or Python

::: incremental
- Analysis is always reproducible with little effort
- free
- extensive support
- R or Python
  - R is easier to understand for users with limited coding experience
  - Python is faster in incorporating cutting-edge algorithms
  - transfer from R to Python or vice versa is easy
  - Quarto supports both R and Python even simultaneously in the same project

:::

## Quantitative Analysis


::: incremental

1. **Logical Model** based on domain knowledge.  
   *Example:* A new webdesign should help increase sales.
   
2. **Quantitative Model** that is general. It is not fitted to data (*unfitted model*)  
   *Example:* The daily mean the sales amount for the new webdesign should be higher than the one for the original webdesign
   
3. **Sample Statistics** based on a sample of $N$ observations that confirms what was stated under topic 2 (or not)  
   **Example:** Track sales on both websites with randomly assigned users over 365 days and calculate the sample means. Compare the sample means and *additionally* run tests if your results are reliable (significant).  
   **Note:** The means you calculated from the sample are not the same as the means mentioned under topic 2. They are only **estimates** of the general (population) means.
   
:::

## Major Data Types




```{mermaid, echo=false, code-fold=false}
graph TD
VarGeneral["Data in General"]
VarChar["Labels/Char:<br/>- Last names<br/>- ZIP-codes<br/>- ID-numbers"]
VarCategory["Categorical/Factors<br/>limited number of variations:<br/>- Sex (male/female)<br/>- Grades (A, B, C, D, F)<br/>- Gender (Male, Female, Non-binary)"]
VarNumeric["Numerical Data<br/>- Counts (number of accident)<br/>- Measures (e.g., Weight; 160.8)"]
VarNumericCon["Continous/Num<br/>- Measures (e.g., Weight; 160.8)"]
VarInt["Discrete/Int<br/>- Counts (e.g., Number of accidents)"]


VarGeneral --> VarChar
VarGeneral --> VarCategory
VarGeneral --> VarNumeric
VarNumeric --> VarInt
VarNumeric --> VarNumericCon


%% Define one reusable style
classDef ClassTopNodeCL text-align:center,color:#000000,fill:#ffffff,stroke:#000000,stroke-width:3.8px;

classDef ClassLowNodesCL text-align:left,color:#0000dd,fill:#dedea9,stroke:#ffffff,stroke-width:3.8px;

classDef ClassLowestNodesCL text-align:left,color:#0000dd,fill:#b3672b,stroke:#ffffff,stroke-width:3.8px;

%% Apply it to multiple nodes
class VarChar,VarNumeric,VarNumericCon,VarInt,VarCategory ClassLowNodesCL;
class VarGeneral ClassTopNodeCL;
class VarNumericCon,VarInt ClassLowestNodesCL
```