---
title: "Standard Deviation and Normal Distribution"
subtitle: "Review"
format: 
  revealjs:
    code-fold: false
    incremental: false
    scrollable: true
    echo: true
---



## What Will You Learn {.scrollable .smaller}
```{r}
#| echo: false
library(kableExtra)

```
-   You will review the concept of Variance to measure the spread of a variable.
-   You will review the concept of Standard Deviation to measure the spread of a variable.
- You will explain  why Standard Deviation is so important for the concept of Normal Distribution.

 

## Some Questions to Introduce Spread

- Who runs faster, men or women?
  (true for all men and women?)

- Who is taller, men or women?
  (true for all men and women?)

- What is it the average temperature in Michigan/Coastal California?

- Which of your products shows high or low volatility in sales?
  (Why? Why is it importan?)
  
## CL Proceed like this

- how to measure center
- how to visualize center and spread (use rel. (percentage) freq).
- histogram with normal distributed data for sales in by sales agent (1000 agents)
- closing results per customer visit

- rolling a die
 -define normal, uniform and Bernoulli
!!! Histograms show distributions

How to measure center and spread

- mean and median

- mean absolut deviation standard deviation (variance) all work but have advantages and disadvantages

Comparing mens ad womens height goes just to the end. So it is just before AB 