---
title: "DRAFT: CAFE’s Summer Institute 2026<br>--- AI Retrofit ---"
subtitle: "Generative AI in Education --- Problems & Opportunities"
date: 5/29/2026

author:
  name: "Carsten Lange"
  email: "clange@cpp.edu"
  affiliation: "Department of Economics, Cal Poly, Pomona"

execute:
  message: false
  warning: false

format: 
  revealjs:
    warning: false
    controls: true
    chalkboard:
      theme: whiteboard
      boardmarker-width: 2.7
    incremental: false
    scrollable: true
    footer: "<a href=https://ai.lange-analytics.com</a> "
---

## Problems & Opportunities {.smaller}

- Dealing with Cheating
- Using *genAI* for Assisted Homeworks
- Teaching *genAI* Design
- *genAI* Learning (teach me how to ...)

## Cheating in Homeworks and Quizzes

`Cheating is not new in academia, but the ease it can be done with genAI is new!`

**Examples:**

- Write a paper about the civil war
- [Cheating related to take-home and online quizzes](https://econ.lange-analytics.com/HomeworkQLive/HW6061/HW6061.html){target="_blank"} <br>
  (Google Lens is in "Hamburger Menu" -> Search with Lens)

## Cheating in Homeworks and Quizzes

`We need to be creative! We need to fight technology with technology! Restrictions are not helping!`

**A few ideas:**

**Small Grade Weights:** Assign small weights to take home assignments and online quizzes

**Strict University Policies for midterm and final proctoring:**

- Phone drop, big classrooms, etc.
- Screen share for online work in our labs
- Lock-Down Browser like 'Respondus'
- Proctoring Centers for a limited amount of homeworks and online quizzes (computers can be very basic)

## Using *genAI* for Assisted Homeworks {.smaller}

`Cheating Allowed:` **Students prepare assignments at home with *genAI* and finalize them in a proctored environment in class**

**Examples:**

- **Paper about Civil War**
  - students prepare the papers at home with the use of genAI and report about the process
  - instructor reads papers before class but does not provide the feedback before the class session
  - students finish the paper without AI in a proctored environment

. . .

- **Statistics and Econometrics**
  - students analyze data with statistical tools like *R* at home with the use of genAI and report about the process
  - instructor reviews the research before class but does not provide the feedback before the class session
  - during a proctored class session students are asked to improve or extend the research determined by the instructor

  . . .

  **Course Assistants**<br>
  (You login to your `Cal Poly ChatGPT` account and then email [clange@cpp.edu](mailto:clange@cpp.edu))

  E.g., [EC 4447/5558 - Artificial Intelligence and Machine Learning for Economic Research
](https://chatgpt.com/g/g-6827f51eb67c819183c5a25885e226a3-machlearn-course-exp-possibly-wrong-answers){target="_blank"}

## Teaching *genAI* Design

- [The Art of Thinking --- challenge, answer or expanded Philosophy topics](https://chatgpt.com/g/g-69e1a37155e48191bc3590359b82c066-the-art-of-thinking)){target="_blank"}
- [Bronco Broject Advisor](https://chatgpt.com/g/g-6a02b1c041e481918eb84471103b0e55-broncoproject-advisor)){target="_blank"}
- [The Last Word --- I never lost an argument](https://chatgpt.com/g/g-6a02b1c041e481918eb84471103b0e55-broncoproject-advisor)){target="_blank"}

## genAI Learning (teach me how to ...)

`UseFlipped Classroom (this is an old concept) where genAI teaches the basics and the instructor focusses on higher skills in the classroom` 

  - fact and skills learning at home
    - use *genAI*: please teach me about ... (example follows)
    - students use textbooks or videos to verify what the learned from *Gemini*
  - higher skills and questions are covered in the classroom

  ## genAI Learning (teach me how to ...)

  ***genAI*** **will not substitute instructors. *genAI* will allow us to focus on higher skills, something we always wanted!**