---
title: "Interactive Project: Tune Polynomial Regression to Predict House Prices"
subtitle: Companion Exercises for [Practical Machine Learning with R](https://ai.lange-analytics.com)"
author:
  name: "Carsten Lange"
  email: "clange@cpp.edu"
  affiliation: "Cal Poly, Pomona"
format: live-html
engine: knitr
webr:
  repos:
    - 'https://tidymodels.r-universe.dev'
    - 'https://repo.r-wasm.org'
  packages:
    - rsample
    - tune
    - dplyr
    - janitor
    - recipes
    - yardstick
    - parsnip
    - workflows
---
{{< include ../_extensions/r-wasm/live/_knitr.qmd >}}
{{< include ../_extensions/r-wasm/live/_gradethis.qmd >}}


::: {.content-visible when-runtime="loading"}
::: {.callout-note}

## Please be Patient: Loading R Environment
The interactive R environment and the required packages must be loaded in your browser. This typically takes 1–2 minutes. You can monitor the progress in the bottom-right corner. 

**After packages are loaded, it still takes some time** because the website must run a pre-tuning procedure. Please be patient!!!

When everything is loaded, you get a **"Ready to roll"** message below.
Thank you for your patience!
:::
:::



```{webr}
#| autorun: true
#| echo: false
DataHousing = read.csv("https://ai.lange-analytics.com/data/HousingData.csv") |>
              clean_names("upper_camel") |>
              select(Price, Sqft = SqftLiving)

set.seed(777)

Split8020=initial_split(prop=0.8, strata=Price, 
                       breaks=5, data=DataHousing)

DataTrain = training(Split8020)
DataTest = testing(Split8020)

RecipePoly=recipe(Price~Sqft, data=DataTrain) |>
  step_poly(Sqft, degree = tune(), options = list(raw = TRUE)) 

ModelDesignPoly= linear_reg() |> 
  set_engine("lm") |> 
  set_mode("regression")

TuneWFModelPoly= workflow() |>  
            add_recipe(RecipePoly) |> 
            add_model(ModelDesignPoly) 

ParGrid=data.frame(degree=c(1:10))

FoldsForTuning=vfold_cv(DataTrain, v=5, strata=Price)

TuneResults=TuneWFModelPoly |> tune_grid(FoldsForTuning, grid=ParGrid , metrics=metric_set(rmse, mae, rsq))

BestHyperPar=select_best(TuneResults, metric="rsq")

WFModelBest=TuneWFModelPoly |> 
            finalize_workflow(BestHyperPar) |>  
            fit(DataTrain)

DataTestWithPredBestModel=augment(WFModelBest,DataTest)

cat("\033[1;32mReady to roll\033[0m\n")
```



**Libraries** already loaded in the background:

- *tidyverse*
- *tidymodels*



**Step 1 - Generating Training and Testing Data:**

As before, you use the housing dataset and split the data into training
(`DataTrain`) and testing data (`DataTest`). Complete the `______` in the code below to assign 80% of the data to the *training data* and 20% to the *testing data*

```{webr}

#| exercise: exc_step1
#| exercise.setup: exc_all
Split8020=initial_split(prop=______, strata=Price, 
                       breaks=5, data=DataHousing)
print(Split8020)
```

::: {.hint exercise="exc_step1"}
**Here is a hint:**

The `prop=` argument determines the proportion of *training data* observations. The remaining observations become *testing data*.
:::

::: {.solution exercise="exc_step1"}
**Here is the Solution:**


```{webr}
#| exercise: exc_step1
#| solution: true
Split8020=initial_split(prop=0.8, #<1>
                        strata=Price, breaks=5, #<2>
                        data=DataHousing)
print(Split8020)
```

1. `prop=0.8` determines that 80% of the data are assigned to the *training data*. All other observations are assigned to the *testing data*.
2.  `strata=Price` ensures that the mean price in *training* and *testing data* observations is similar. The `breaks=5` argument ensures that this is true for all quintiles.

:::

```{webr}
#| exercise: exc_step1
#| check: true
gradethis::grade_this_code()
```

**Step 2 - Create a Recipe:**

Here, you will create a *recipe* and store it in the *R* object
`RecipePoly`. 

The recipe creautes the variables for $Sqft^2$, $Sqft^3$ and so on, depending on which degree is chosen.

Since you plan to tune the argument
`degree=`, you have
to add the placeholder `tune()`. Remember that you cannot set `degree` to a specific
numerical value because you want to *tune* the *hyper-parameter*
`degree` later on. 

Note that the data frame `DataTrain` has already been loaded in the
background:

```{webr}
#| exercise: exc_step2
#| exercise.setup: exc_all
RecipePoly=recipe(Price~Sqft, data=DataTrain) |>
  step_poly(Sqft, degree = ______, options = list(raw = TRUE)) 
print(RecipePoly)
```

::: {.hint exercise="exc_step2"}
**Here is a hint:**

You have to assign the placeholder `tune()` to the argument `degree=`. Later, when you tune the workflow, it will be replaced by the values you choose to try out.
:::

::: {.solution exercise="exc_step2"}
**Here is the Solution:**


```{webr}
#| exercise: exc_step2
#| solution: true
RecipePoly=recipe(Price~Sqft, data=DataTrain) |>
  step_poly(Sqft, degree = tune(), options = list(raw = TRUE)) 
print(RecipePoly)
```
:::

```{webr}
#| exercise: exc_step2
#| check: true
gradethis::grade_this_code()
```

**Step 3 - Create a Model Design:**

Next, you will create the *model design* and store it into the *R*
object `ModelDesignPoly`. It is exactly the same that you use for a linear regression. 

```{webr}
#| exercise: exc_step3
#| exercise.setup: exc_all
ModelDesignPoly= ______() |> 
  set_engine("lm") |> 
  set_mode("______")
  print(ModelDesignPoly)
```

::: {.hint exercise="exc_step3"}
**Here is a hint:**

1. The `tidymodels` command for a linear regression is `linear_reg()`
2. Your ananlysis is a *regression* not a *classification*
:::

::: {.solution exercise="exc_step3"}
**Here is the Solution:**

```{webr}
#| exercise: exc_step3
#| solution: true
ModelDesignPoly= linear_reg() |> 
  set_engine("lm") |> 
  set_mode("regression")
print(ModelDesignPoly)
```
::: 

```{webr}
#| exercise: exc_step3
#| check: true
gradethis::grade_this_code()
```

**Step 4 - Add the RecipePoly and the Model Design to a Workflow:**

The code block below adds the *R* object `Recipe` and the model
design object `ModelDesignPoly` to a *workflow* model named
`TuneWFModelPoly`. The *R* code has been executed already.

```{webr}
#| autorun: true
#| exercise.setup: exc_all
TuneWFModelPoly= workflow() |>  
            add_recipe(RecipePoly) |> 
            add_model(ModelDesignPoly)
print(TuneWFModelPoly)
```

You can see in the printout above that the *workflow* is not *finalized* because  `degree` has not been set in    the *model design*. The *hyper-parameter* `degree` is set to
`tune()` instead. Later, in Step 7, `tune()` will be replaced in a trial
and error process with different values for `degree`.

**Step 5 - Create a Hyper-Parameter Grid:**

When tuning is executed in Step 7, values reaching from 1 -- 10 for the *hyper-parameter* `neighbors` shall be tried out. You need to provide these values in a data frame column that is named the same as the *hyper-parameter*. Below, replace the `______` to define a column `degree` in the data frame`ParGrid`. The column should contain values from 1 -- 10:

```{webr}
#| exercise: exc_step5
#| exercise.setup: exc_all
ParGrid=data.frame(degree=c(______))
print(ParGrid)
```

::: {.hint exercise="exc_step5"}
**Here is a hint:**

Use the `c()` command to create a vector containing the numbers $1 - 10$
either separated by a comma, or you can use a colon (*:*) to indicate *from/to*.
:::

::: {.solution exercise="exc_step5"}
**Here is the Solution:**

```{webr}
#| exercise: exc_step5
#| solution: true
ParGrid=data.frame(neighbors=c(1,2,3,4,5,6,7,8,9,10))
ParGrid
```

:::

```{webr}
#| exercise: exc_step5
#| check: true
grade_this({
  # .result refers to the output of the student's code
  if (sum(.result)==sum(1:10)) {
    pass()
  } else {
    fail()
  }
})
```

**Step 6 - Creating Resamples for Cross-Validation:**

The values you have created above for `degree` of the *Polynomial Regression* (*hyper-parameter*
`degree`) will be evaluated later using five folds (*resamples*).

Each fold contains the complete training data, but different 
sections are used for training and assessment in each fold.
Please create five folds below by substituting `______`
accordingly.

The folds will be saved in the *R* object `FoldsForTuning`:

```{webr}
#| exercise: exc_step6
#| exercise.setup: exc_all
set.seed(123)
FoldsForTuning=vfold_cv(DataTrain, v=______, strata=Price)
print(FoldsForTuning)
```

::: {.hint exercise="exc_step6"}
**Here is a hint:**

The argument `v=` determines the number of folds to be used for tuning.
:::

::: {.solution exercise="exc_step6"}
**Here is the Solution:**

```{webr}
#| exercise: exc_step6
#| solution: true
set.seed(123)
FoldsForTuning=vfold_cv(DataTrain, v=5, strata=Price)
print(FoldsForTuning)
```
:::

```{webr}
#| exercise: exc_step6
#| check: true
gradethis::grade_this_code()
```

**Step 7 - Tune the Workflow and Train All Models:**

Now it is time to run the tuning procedure using the `tune_grid()`
command. Be patient because it will take some time to fully execute.
Since we have to try out 10 parameters and use five folds for each
model, the `tune_grid()` command has to fit 50 models
$(10\cdot 5=50)$.

Please substitute `______` with a list of metrics to be
calculated. Use the metrics `rmse` (*Root Mean Squared Error*), `mae` (*Mean Absolute Error*) and `rsq` (*r Squared* $r^2$).

After the tuning is finished, all results are stored in the *R*
object `TuneResults`, and they can be evaluated by different
*metrics* commands.

For example the command `autoplot()` provides a diagrammatic
overview of the results for the three *metrics*.

```{webr}
#| exercise: exc_step7
#| exercise.setup: exc_all
TuneResults=tune_grid(TuneWFModelPoly, resamples=FoldsForTuning,
                      grid=ParGrid, metrics=metric_set(______))
autoplot(TuneResults)
```

::: {.hint exercise="exc_step7"}
**Here is a hint:**

The command `metric_set()` takes a comma-separated list 
of metrics to be evaluated.

Consider that you want to evaluate the metrics `rmse`, `mae`, and `rsq`.
:::

::: {.solution exercise="exc_step7"}
**Here is the Solution:**

```{webr}
#| exercise: exc_step7
#| solution: true
TuneResults=tune_grid(TuneWFModelPoly, resamples=FoldsForTuning,
                      grid=ParGrid, metrics=metric_set(rmse, mae, rsq))
autoplot(TuneResults)
```
:::

```{webr}
#| exercise: exc_step7
#| check: true
gradethis::grade_this_code()
```

The three graphs that you created in the exercise above show the values for
each *rmse*, *mae*, and *rsq* for all tried out *hyper-parameters* (`degree`).

To calculate these values  the five folds that were used for validation are averaged.

It looks like $r^2$ has the clearst fluctutions. It seems reasonable to assume that `degree=6` provides the best results. Let us confirm this in the *Step 8.*

**Step 8 - Extract the Best Hyper-Parameter(s):**

All assessment results for the specified metrics are stored in the
*tuning* object `TuneResults`. Choose the metric *rsq* by
substituting `______` accordingly. Afterward, when you execute the
code the `select_best()` command extracts the best *hyper-parameter*
(value for `degree`) for the metric you specified:

```{webr}
#| exercise: exc_step8
#| exercise.setup: exc_all
BestHyperPar=select_best(TuneResults, metric="______") 
print(BestHyperPar)
```

::: {.hint exercise="exc_step8"}
**Here is a hint:**

Substitute `______` with `rsq` and make sure to not delete the quotes.
:::

::: {.solution exercise="exc_step8"}
**Here is the Solution:**

```{webr}
#| exercise: exc_step8
#| solution: true
BestHyperPar=select_best(TuneResults, metric="rsq") 
print(BestHyperPar)
```
:::

```{webr}
#| exercise: exc_step8
#| check: true
gradethis::grade_this_code()
```

As you will see in the printout after executing the *R* code, the
best value for the *hyper-parameter* `degree` based on *rsq*
is $degree=6$. It is
saved in the data frame `BestHyperPar`.

You can try other metrics in the code block above and see if the
result changes. 

**Step 9 - Finalize and Train the Best Workflow Model:**

The code block below is executed already. The `finalize_workflow()`
command used the value from `BestHyperPar` to substitute the
`tune()` placeholder in the *R* object `TuneWFModelKNN` (created in
Steps 2 -- 4). The *hyper-parameter* is now set to $degree=6$ .

    
```{webr}
#| autorun: true
#| exercise.setup: exc_all
WFModelBest=TuneWFModelPoly |> 
            finalize_workflow(BestHyperPar) |>  
            fit(DataTrain)

print(WFModelBest)
```

At the end of the printout above, you can see that a Degree 6 Polynominal Regression is used and waht the related coefficients are.

**Step 10: Assess Prediction Quality Based on the Testing Data:**

Since `WFModelBest` is a fitted model, you can use it for
predictions. In this last step, you use the `augment()` command to
predict house prices (`Price`). The `augment()` command will then add the
prediction results as column `.pred` to the testing data.

The `metric()` command compares the predictions in column `.pred`
to the true values to calcualte common metrics for a regression. But before, you
have to substitute `______` with the variable name
(column name) for the outcome variable.

```{webr}
#| exercise: exc_step10
#| exercise.setup: exc_all
DataTestWithPredBestModel=augment(WFModelBest, DataTest)    
metrics(DataTestWithPredBestModel, truth=______, estimate=.pred)
```

::: {.hint exercise="exc_step10"}
**Here is a hint:**

The (column) name for the outcome variable is `Price` and the predictions are stored in the column `.pred`.
:::

::: {.solution exercise="exc_step10"}
**Here is the Solution:**

```{webr}
#| exercise: exc_step10
#| solution: true
DataTestWithPredBestModel=augment(WFModelBest, DataTest)    
metrics(DataTestWithPredBestModel, truth=Price, estimate=.pred)
```
:::


