---
title: "Introduction"
author:
  name: "Carsten Lange"
  email: "clange@cpp.edu"
  affiliation: "Cal Poly, Pomona"

format: 
  revealjs:
    echo: true
    code-fold: true
    output-location: fragment
    incremental: false
    warning: false
    message: false
    navigation-mode: vertical
    scrollable: true
    smaller: true
   
  
    
include-in-header:
  text: |
    <style>
    .reveal .slides section:not(:first-of-type) h1,
    .reveal .slides section:not(:first-of-type) h2,
    .reveal .slides section:not(:first-of-type) h3,
    .reveal .slides section:not(:first-of-type) h4,
    .reveal .slides section:not(:first-of-type) h5,
    .reveal .slides section:not(:first-of-type) h6 {
      font-size: 142% !important;
    }
    </style>
    
---

## Success in The Course

::: incremental
- Use AI responsible
- Read the textbook
- Follow the Learning Guide!!!
- Take notes
- Ask questions
- Don't be lame
:::

## Quantitative Analysis

::: incremental

1. **Logical Model** based on domain knowledge.  
   *Example:* A new web-design should help increase sales.
   
2. **Quantitative Model (unfitted)** The model is general, and it is not fitted to data  
   *Example:* The daily mean the sales amount for the new web-design should be higher than the one for the original web-design
   
3. **Sample Statistics (fitting the model to available data)** based on a sample of $N$ observations that confirms what was stated under topic 2 (or not)  
   **Example:** Track sales on both websites with randomly assigned users over 365 days and calculate the sample means. Compare the sample means and *additionally* run tests if your results are reliable (significant).  
   **Note:** The means you calculated from the sample are not the same as the means mentioned under topic 2. They are only **estimates** of the general (population) means.
   
:::

