<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.31">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Carsten Lange">

<title>Multimedia ANOVA Testing for Website Conversions</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Anova_files/libs/clipboard/clipboard.min.js"></script>
<script src="Anova_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Anova_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Anova_files/libs/quarto-html/popper.min.js"></script>
<script src="Anova_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Anova_files/libs/quarto-html/anchor.min.js"></script>
<link href="Anova_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Anova_files/libs/quarto-html/quarto-syntax-highlighting-e1a5c8363afafaef2c763b6775fbf3ca.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Anova_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Anova_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Anova_files/libs/bootstrap/bootstrap-bb462d781dde1847d9e3ccf7736099dd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="Anova.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Multimedia ANOVA Testing for Website Conversions</h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Carsten Lange <a href="mailto:clange@cpp.edu" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            California State Polytechnic University Pomona
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  


</header>


<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>Imagine you are in charge of optimizing a company’s website. The goal is simple: increase conversions — defined here as users clicking on the ordering form. The marketing team proposes a solution: <strong>Enhance the website with either audio or video content to better engage visitors.<br>
</strong>But will these multimedia upgrades actually drive more clicks, or will the effort fall flat?</p>
<p>To answer this question, the company decides to run a controlled experiment. Every website visitor is randomly redirected to one of three versions of the site:</p>
<ul>
<li>the original (<strong>Control</strong>),</li>
<li>one enhanced with <strong>Audio</strong>, or</li>
<li>one enhanced with <strong>Video</strong>.</li>
</ul>
<p>Afterward, the team tracks hourly conversions for each of the three scenarios (<em>Control</em>, <em>Audio</em>, <em>Video</em>). The result generated a randomized dataset, ideal for testing whether the <em>Audio</em>, <em>Video</em> treatments have a measurable impact on user behavior.</p>
<p>In this article, we will walk through a simulated version of this marketing experiment using artificial data adapted from the well-known Palmer Penguins dataset. The setup mirrors how real companies might structure and evaluate a digital content strategy.</p>
</section>
<section id="experimental-design" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Experimental Design</h1>
<p>To assess the impact of multimedia content on user behavior, the company conducted a randomized test involving three website variants:</p>
<ul>
<li><strong>Control</strong>: the original site with no enhancements<br>
</li>
<li><strong>Audio</strong>: the same site augmented with audio content<br>
</li>
<li><strong>Video</strong>: the site upgraded with embedded video content</li>
</ul>
<p>Every visitor arriving at the website was randomly assigned to one of these three groups. The primary metric of <strong>conversion</strong> was defined as whether users clicked on the ordering form. Each record reflects one hour of user data for the three scenarios leading to a total of 342 observations.</p>
</section>
<section id="data-generation-and-structure" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Data Generation and Structure</h1>
<p>To simulate this experiment, a proxy dataset was created using the well-known <strong>Palmer Penguins</strong> dataset. In this synthetic version:</p>
<ul>
<li>The variable <strong>flipper length</strong> was reinterpreted to represent the <strong>number of conversions</strong> within a one-hour period.</li>
<li>The <strong>species</strong> of the penguins was repurposed as the <strong>treatment group</strong> (<strong>Control</strong>, <strong>Audio</strong>, or <strong>Video</strong>).</li>
</ul>
<p>Although artificial, this approach allows us to explore realistic patterns in conversion behavior under different digital content strategies.</p>
<p>The code below shows how the Palmer Penguin dataset was used to generate the dataset and which R libraries were used:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co">#library(kableExtra)</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(palmerpenguins)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>DataWeb<span class="ot">=</span>penguins <span class="sc">|&gt;</span> </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>       <span class="fu">select</span>(<span class="at">Conversions=</span>flipper_length_mm, <span class="at">Treatment=</span>species) <span class="sc">|&gt;</span> </span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>       <span class="fu">drop_na</span>()</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(DataWeb<span class="sc">$</span>Treatment)<span class="ot">=</span><span class="fu">c</span>(<span class="st">"Control"</span>, <span class="st">"Audio"</span>, <span class="st">"Video"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Each observation shows for different web design scenarios how many conversions resulted within 1 hour. The first 6 records are shown in <a href="#tbl-firstsix" class="quarto-xref">Table&nbsp;1</a>:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">sample_n</span>(DataWeb,<span class="dv">6</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="tbl-firstsix" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-firstsix-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: First Six Observations from the Dataset
</figcaption>
<div aria-describedby="tbl-firstsix-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">Conversions</th>
<th style="text-align: left;">Treatment</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">215</td>
<td style="text-align: left;">Video</td>
</tr>
<tr class="even">
<td style="text-align: right;">198</td>
<td style="text-align: left;">Control</td>
</tr>
<tr class="odd">
<td style="text-align: right;">216</td>
<td style="text-align: left;">Video</td>
</tr>
<tr class="even">
<td style="text-align: right;">201</td>
<td style="text-align: left;">Audio</td>
</tr>
<tr class="odd">
<td style="text-align: right;">189</td>
<td style="text-align: left;">Control</td>
</tr>
<tr class="even">
<td style="text-align: right;">195</td>
<td style="text-align: left;">Audio</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="group-and-overall-means" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Group and Overall Means</h1>
<p>The code below generates group means for the <em>Control</em>, <em>Audio</em>, and <em>Video</em> groups, together with the overall mean (<em>GrandMean</em>) across all groups and outputs the results in <a href="#tbl-means" class="quarto-xref">Table&nbsp;2</a>:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>GrandMean  <span class="ot">=</span> <span class="fu">mean</span>(DataWeb<span class="sc">$</span>Conversions)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Conditional Means by Treatment</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>MeansByTreatment <span class="ot">&lt;-</span> DataWeb <span class="sc">%&gt;%</span> </span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Treatment) <span class="sc">%&gt;%</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Mean =</span> <span class="fu">mean</span>(Conversions), <span class="at">N=</span><span class="fu">n</span>())<span class="sc">|&gt;</span> </span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_rows</span>(<span class="fu">tibble</span>(</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">Treatment =</span> <span class="st">"Overall"</span>,</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">Mean =</span> GrandMean,</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">N =</span> <span class="dv">342</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>N<span class="ot">=</span><span class="dv">342</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="co"># View results</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(MeansByTreatment)</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="co"># |&gt; </span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a><span class="co">#    kable_styling(full_width = FALSE, position = "center")%&gt;%    scroll_box(width = "400px")</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="tbl-means" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-means-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Overall Mean and Means of the Treatments
</figcaption>
<div aria-describedby="tbl-means-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Treatment</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">N</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Control</td>
<td style="text-align: right;">189.9536</td>
<td style="text-align: right;">151</td>
</tr>
<tr class="even">
<td style="text-align: left;">Audio</td>
<td style="text-align: right;">195.8235</td>
<td style="text-align: right;">68</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Video</td>
<td style="text-align: right;">217.1870</td>
<td style="text-align: right;">123</td>
</tr>
<tr class="even">
<td style="text-align: left;">Overall</td>
<td style="text-align: right;">200.9152</td>
<td style="text-align: right;">342</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>At a glance, both multimedia-enhanced designs resulted in a higher average number of conversions per hour compared to the control group.</p>
<p>Notably, the <em>Video</em> variant had the highest mean, with an average of 217.19 conversions — nearly 27 more than the Control.</p>
<p>The Audio variant also outperformed the Control, though with a smaller gap.</p>
<p>The Control group had the lowest mean but the largest sample size.</p>
<p>The Grand Mean of 200.92 provides a useful benchmark for understanding overall performance across all treatments, especially when considering statistical comparisons or variance analysis.</p>
<p><a href="#fig-treatmentmeans" class="quarto-xref">Figure&nbsp;1</a> provides additional evidence for this impression:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(DataWeb, <span class="fu">aes</span>(<span class="at">y=</span><span class="dv">0</span>, <span class="at">x =</span> Conversions, <span class="at">color =</span> Treatment)) <span class="sc">+</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> MeansByTreatment[[<span class="dv">1</span>,<span class="dv">2</span>]], <span class="at">color =</span> <span class="st">"red"</span>,<span class="at">linewidth=</span><span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> MeansByTreatment[[<span class="dv">2</span>,<span class="dv">2</span>]], <span class="at">color =</span> <span class="st">"green"</span>,<span class="at">linewidth=</span><span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> MeansByTreatment[[<span class="dv">3</span>,<span class="dv">2</span>]], <span class="at">color =</span> <span class="st">"blue"</span>,<span class="at">linewidth=</span><span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(DataWeb<span class="sc">$</span>Conversions), <span class="at">color =</span> <span class="st">"black"</span>,<span class="at">linewidth=</span><span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">""</span>) <span class="sc">+</span>              <span class="co"># Set y-axis title</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="cn">NULL</span>)<span class="sc">+</span> </span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> MeansByTreatment[[<span class="dv">1</span>,<span class="dv">2</span>]], <span class="at">y =</span> <span class="fl">0.37</span>, </span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">label =</span> <span class="fu">round</span>(MeansByTreatment[[<span class="dv">1</span>,<span class="dv">2</span>]],<span class="dv">2</span>), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">angle =</span> <span class="dv">90</span>, </span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">3</span>)<span class="sc">+</span> </span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> MeansByTreatment[[<span class="dv">2</span>,<span class="dv">2</span>]], <span class="at">y =</span> <span class="fl">0.37</span>, </span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">label =</span> <span class="fu">round</span>(MeansByTreatment[[<span class="dv">2</span>,<span class="dv">2</span>]],<span class="dv">2</span>), <span class="at">color =</span> <span class="st">"green"</span>, <span class="at">angle =</span> <span class="dv">90</span>, </span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> MeansByTreatment[[<span class="dv">3</span>,<span class="dv">2</span>]], <span class="at">y =</span> <span class="fl">0.37</span>, </span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">label =</span> <span class="fu">round</span>(MeansByTreatment[[<span class="dv">3</span>,<span class="dv">2</span>]],<span class="dv">2</span>), <span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">angle =</span> <span class="dv">90</span>, </span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="fu">mean</span>(DataWeb<span class="sc">$</span>Conversions), <span class="at">y =</span> <span class="fl">0.37</span>, </span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">label =</span> <span class="fu">round</span>(<span class="fu">mean</span>(DataWeb<span class="sc">$</span>Conversions),<span class="dv">2</span>), <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">angle =</span> <span class="dv">90</span>, <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">3</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-treatmentmeans" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-treatmentmeans-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Anova_files/figure-html/fig-treatmentmeans-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-treatmentmeans-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Treatment Means and Grand Means with Data Distribution
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Can we scientifically determine whether these observed differences are statistically significant?</strong></p>
</section>
<section id="why-not-use-pairwise-ab-tests" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Why Not Use Pairwise A/B Tests?</h1>
<p>A tempting idea in this setting is to run multiple pairwise <strong>A/B Tests</strong> to compare each design against the <em>Control</em>:</p>
<ul>
<li><p><strong>Audio</strong> vs.&nbsp;<strong>Control</strong></p></li>
<li><p><strong>Video</strong> vs.&nbsp;<strong>Control</strong></p></li>
</ul>
<p>While intuitive, this approach introduces big statistical concern: increased risk of false positives (<em>Type I Error</em>). That is, by running multiple comparisons independently, we raise the chance of incorrectly concluding that a difference exists when it does not.</p>
<p>Even if each individual test maintains a 5% error rate (<span class="math inline">\(\alpha = 0.05\)</span>), the combined probability of making at least one false discovery across two tests rises to:</p>
<p><span class="math display">\[1−(1−0.05)^2=0.0975\approx 10
\%\]</span></p>
<p>With more variations, the problem compounds quickly. For example, if we had four treatments in addition to the <em>Control</em>, the chance of a false positive somewhere among those comparisons would rise to nearly 20%:</p>
<p><span class="math display">\[1−(1−0.05)^2=0.1855\approx 20 \%\]</span></p>
<p>Clearly, this inflation of error makes multiple pairwise<br>
<em>A/B Tests</em> <strong>statistically unreliable</strong>.</p>
<p><strong>A Better Alternative:<br>
Testing all treatments at once</strong> instead of running several separate tests. This is where <em>Analysis of Variance</em> or short <em>ANOVA</em> comes in:</p>
<ul>
<li><p><em>ANOVA</em> allows to test one or more groups of variables simultaneously</p></li>
<li><p><em>ANOVA</em> avoids the pitfalls of multiple testing</p></li>
</ul>
<p>However, if the ANOVA result is significant, we know only that at least one, but not which one(s) of the variables are significant. Afterward, more testing is needed to find out which variable is significant.</p>
</section>
<section id="regression-and-anova" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Regression and ANOVA</h1>
<p>One way to approach <em>ANOVA</em> is through regression analysis. The idea is simple: if any of the treatment types (<em>Audio</em> or <em>Video</em>) has an impact on conversions, then including these variables in a regression model should improve its explanatory power.</p>
<p>This is exactly what we explore below. We fit a linear model with <strong>Treatment</strong> as a categorical predictor of <strong>Conversions</strong>:</p>
<p><span class="math display">\[Conv_i=\beta_1 Audio_i+\beta_2 Video_i+ \beta_0\]</span> Here, <span class="math inline">\(Audio_i\)</span> and <span class="math inline">\(Video_i\)</span> are dummy variables for group membership. The <strong>Control group</strong> is omitted and serves as the <strong>reference category</strong>.</p>
<p>The code below runs the analysis in <em>R</em>, stores the model in the object <code>ModelLM</code>, and displays the summary output in <a href="#tbl-LM" class="quarto-xref">Table&nbsp;3</a> with <code>summary()</code>.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>ModelLM <span class="ot">=</span> <span class="fu">lm</span>(Conversions <span class="sc">~</span> Treatment, <span class="at">data =</span> DataWeb)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>TableLM<span class="ot">=</span><span class="fu">summary</span>(ModelLM) <span class="sc">|&gt;</span> </span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">tidy</span>() </span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(TableLM) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="tbl-LM" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-LM-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Output from the Linear Regression
</figcaption>
<div aria-describedby="tbl-LM-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">189.953642</td>
<td style="text-align: right;">0.5404799</td>
<td style="text-align: right;">351.453643</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">TreatmentAudio</td>
<td style="text-align: right;">5.869887</td>
<td style="text-align: right;">0.9699452</td>
<td style="text-align: right;">6.051772</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TreatmentVideo</td>
<td style="text-align: right;">27.233349</td>
<td style="text-align: right;">0.8066819</td>
<td style="text-align: right;">33.759714</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>At first glance, the <em>t-values</em> for the treatment coefficients may suggest statistical significance. However, due to the <strong>multiple testing problem</strong>, we cannot rely on these individual <em>t-tests</em> for a <em>multi-variable</em> comparison. Doing so would increase the risk of an inflated <em>Type I error</em> — falsely concluding that a difference exists when it does not.</p>
<section id="from-regression-to-anova" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="from-regression-to-anova"><span class="header-section-number">6.1</span> From Regression to ANOVA</h2>
<p>So, if multiple <em>t-test</em> are not an option:</p>
<p><strong>What can we do instead?</strong></p>
<p>Rather than testing each treatment effect separately, we assess their combined influence on the model. In other words:</p>
<p><strong>Does adding the Treatment variables simultaneously improve the model vs.&nbsp;no treatment effect at all?</strong></p>
<p>This is precisely what <em>ANOVA</em> measures in the context of regression — it compares the <strong>explained variance of the full model (with Treatment)</strong> to a <strong>restricted model (intercept-only in our case)</strong> using an <strong>F-test.</strong></p>
<p>The <strong>restricted model</strong> model can be written like this:</p>
<p><span class="math display">\[
Conv_i=\beta_0 \qquad \mbox{ with: } \quad\beta_0=\frac{\sum_{i=1}^N Conv_i}{N}
\]</span></p>
<p>In other words, the <em>restricted model</em> predicts every observation using only the <strong>Grand Mean</strong> (mean of all <span class="math inline">\(Conversions\)</span>).</p>
<p>To quantify the improvement of the <em>Full</em> model over the <em>Restricted</em> model based on the Total Sum of Squared Errors (<span class="math inline">\(SSE\)</span>), we calculate the <em>F-value</em> as follows:</p>
<p><span id="eq-FValueOrg"><span class="math display">\[
F = \left(\frac{SSE_{restr}-SSE_{full}}{df_{restr}-df_{full}} \right ) \div
     \left(\frac{SSE_{full}}{df_{full}} \right )
\tag{1}\]</span></span> <span class="math display">\[
\Longleftrightarrow\]</span> <span id="eq-FValue"><span class="math display">\[
F = \overbrace{\frac{SSE_{restr}-SSE_{full}}{SSE_{full}}}^{
\begin{array}{c}\text{Proportional Improvement}\\
                \text{(restr. to full model)}
\end{array}} \cdot
   \overbrace{\frac{df_{full}}{df_{restr}-df_{full}}}^{C_{onst}}
\tag{2}\]</span></span></p>
<p>Source: <a href="https://online.stat.psu.edu/stat501/lesson/6/6.2" class="uri">https://online.stat.psu.edu/stat501/lesson/6/6.2</a></p>
<div class="p-3 bg-secondary rounded">
<p><strong>The larger the <span class="math inline">\(F-\)</span>value, the more improves the full model over the restricted model — the more important are the treatments (<em>Audio</em>,<em>Video</em>) for conversions.</strong></p>
</div>
</section>
<section id="break-down-the-f-value-formula" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="break-down-the-f-value-formula"><span class="header-section-number">6.2</span> Break Down the F-Value Formula</h2>
<p><strong>The Right Multiplier (is constant):</strong></p>
<blockquote class="blockquote">
<p>The second term in the formula — the right-hand multiplier — is constant once the experimental design is fixed. It depends only on the degrees of freedom of the models:</p>
<ul>
<li><strong>Number of observations:</strong> <span class="math inline">\(N = 342\)</span><br>
</li>
<li><strong>Degrees of freedom for the restricted model (intercept only):</strong><br>
<span class="math inline">\(df_{\text{restr}} = 342 - 1 = 341\)</span><br>
</li>
<li><strong>Degrees of freedom for the full model (intercept + 2 treatments):</strong><br>
<span class="math inline">\(df_{\text{full}} = 342 - 3 = 339\)</span></li>
</ul>
<p><strong>We can calculate <span class="math inline">\(C^{\text{onst}}\)</span> as follows:</strong></p>
<p><span class="math display">\[
C^{\text{onst}} = \frac{df_{\text{full}}}{df_{\text{restr}} - df_{\text{full}}}
= \frac{342 - 3}{(342 - 1) - (342 - 3)}
= \frac{339}{2}
\]</span> <br><br></p>
</blockquote>
<p><strong>The Left Multiplier: Model Improvement</strong></p>
<blockquote class="blockquote">
<p>The left term in the formula captures how much better the full model is in reducing the squared error:</p>
<p><span id="eq-ProportionOfImprovement"><span class="math display">\[
\frac{SSE_{restr}-SSE_{full}}{SSE_{full}}
\tag{3}\]</span></span> <br> <br></p>
</blockquote>
<div class="p-3 bg-secondary rounded">
<p><strong>With the right multiplier of the F-value equation being constant, it is only the left multiplier that determines if F is large or not.</strong></p>
</div>
<p><span class="math display">\[
F = \overbrace{\frac{SSE_{restr}-SSE_{full}}{SSE_{full}}}^{
\begin{array}{c}\text{Proportional Improvement}\\
                \text{(restr. to full model)}
\end{array}} \cdot
   \overbrace{\frac{df_{full}}{df_{restr}-df_{full}}}^{C_{onst}}
\]</span></p>
</section>
<section id="calculating-the-sses-in-r" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="calculating-the-sses-in-r"><span class="header-section-number">6.3</span> Calculating the SSEs in R</h2>
<p>To compute the <span class="math inline">\(SSE\)</span> values for both models and derive the F-statistic, we use the <code>anova()</code> function for a linear model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>ModelAnova<span class="ot">=</span><span class="fu">anova</span>(ModelLM)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The code below outputs the related <em>ANOVA</em> table and adds a row for the <em>restricted model</em> (Intercept).</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>ModelAnovaRestr<span class="ot">=</span><span class="fu">anova</span>(<span class="fu">lm</span>(Conversions<span class="sc">~</span><span class="dv">1</span>, <span class="at">data=</span>DataWeb))</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>FancyOutput<span class="ot">=</span><span class="fu">rbind</span>(broom<span class="sc">::</span><span class="fu">tidy</span>(ModelAnovaRestr), </span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>                  broom<span class="sc">::</span><span class="fu">tidy</span>(ModelAnova)) <span class="sc">|&gt;</span> </span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">select</span>(<span class="sc">-</span>p.value)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>FancyOutput[<span class="dv">1</span>,<span class="dv">1</span>]<span class="ot">=</span><span class="st">"Intercept (ModelRestr)"</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>FancyOutput[<span class="dv">3</span>,<span class="dv">1</span>]<span class="ot">=</span><span class="st">"Residuals (ModelFull)"</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(FancyOutput)<span class="ot">=</span><span class="fu">c</span>(<span class="st">"Term"</span>,<span class="st">"df"</span>, <span class="st">"SSE"</span>,<span class="st">"MeanSq"</span>,<span class="st">"F-Value"</span>)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(FancyOutput) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="tbl-ANOVA" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ANOVA-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Ammended anova() Output
</figcaption>
<div aria-describedby="tbl-ANOVA-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Term</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">SSE</th>
<th style="text-align: right;">MeanSq</th>
<th style="text-align: right;">F-Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept (ModelRestr)</td>
<td style="text-align: right;">341</td>
<td style="text-align: right;">67426.54</td>
<td style="text-align: right;">197.7318</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Treatment</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">52473.28</td>
<td style="text-align: right;">26236.6419</td>
<td style="text-align: right;">594.8016</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Residuals (ModelFull)</td>
<td style="text-align: right;">339</td>
<td style="text-align: right;">14953.26</td>
<td style="text-align: right;">44.1099</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><br><br></p>
<p>In the ANOVA output generated by <code>anova(ModelLM)</code>, the <strong>F-value</strong> is already reported. However, we will recalculate it below to illustrate the procedure <em>under the hood</em> of the <code>anova()</code> function.</p>
<hr>
<p><strong>Step 1:</strong><br>
The <strong>Sum of Squared Errors</strong> for the <strong>restricted model</strong>, which includes only the intercept (i.e., the grand mean of conversions), is found in the <strong>first row</strong> of the ANOVA <a href="#tbl-ANOVA" class="quarto-xref">Table&nbsp;4</a> , under the <span class="math inline">\(SSE\)</span> column <span class="math inline">\((SSE_{\text{restr}} = 67,\!426)\)</span>.</p>
<p><strong>Step 2:</strong><br>
The <strong>Sum of Squared Errors</strong> for the <strong>full model</strong>, which includes the predictors <em>Audio</em> and <em>Video</em>, is listed in the <strong>Residuals</strong> row (third row) of <a href="#tbl-ANOVA" class="quarto-xref">Table&nbsp;4</a> (<span class="math inline">\(SSE_{\text{full}} = 14,\!953\)</span>).</p>
<blockquote class="blockquote">
<p>🔍 <strong>Note:</strong> The first row of the <a href="#tbl-ANOVA" class="quarto-xref">Table&nbsp;4</a> (labeled <em>Intercept</em>) is included primarily for convenience and interpretability. However, all values required to compute the F-statistic using <a href="#eq-FValue" class="quarto-xref">Equation&nbsp;2</a> can be derived entirely from the <strong>second and third rows</strong> which is the output produced by <code>anova()</code>.</p>
<p>Specifically:</p>
<ul>
<li><span class="math inline">\(SSE_{restr}-SE_{full}=67,\!426-14,\!953=52,\!473.28\)</span> and</li>
<li><span class="math inline">\(df_{restr}-df_{full}= 341-339=2\)</span></li>
</ul>
<p>are both reported in row 2 of <a href="#tbl-ANOVA" class="quarto-xref">Table&nbsp;4</a>.</p>
</blockquote>
<p><strong>Step 3:</strong><br>
We now plug the values from Step 1 and Step 2 together with the related degrees of freedom into the F-statistic formula from <a href="#eq-FValue" class="quarto-xref">Equation&nbsp;2</a>:</p>
<p><span class="math display">\[
F =
\underbrace{\frac{SSE_{\text{restr}} - SSE_{\text{full}}}{SSE_{\text{full}}}}_{
\begin{array}{c}
\text{Proportional Improvement} \\
\text{(restr. to full model)}
\end{array}
}
\cdot
\underbrace{\frac{df_{\text{full}}}{df_{\text{restr}} - df_{\text{full}}}}_{\text{Constant}}
\]</span></p>
<p>Plugging in the values we get:</p>
<p><span class="math display">\[
F =
\underbrace{\frac{67,\!426 - 14,\!953}{14,\!953}}_{
\approx 3.51
}
\cdot
\underbrace{\frac{339}{341-339}}_{= 169.5}
= 3.51 \cdot 169.5
\approx \boxed{594.80}
\]</span></p>
<p>The sum of squared errors (<span class="math inline">\(SSE\)</span>) in the restricted model is approximately <strong>3.5 times larger</strong> than in the full model. Thus reflecting a big improvement through incorporating the treatment effects (<em>Audio</em> and <em>Video</em>).</p>
<p>Multiplying this improvement factor by the constant <span class="math inline">\((169.5)\)</span> yields the <strong>F-value of 594.8</strong>, as reported in the ANOVA output. This same value also appears in the <code>summary()</code> output for the linear regression model, confirming consistency across both methods of evaluation.</p>
</section>
</section>
<section id="f-value-when-is-large-large-enough-for-significance-needs-editing-work-by-cl" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> F-value: When is Large Large Enough for Significance (needs editing work by CL!)</h1>
<p>In the previous section we derived an F-value of <span class="math inline">\(F=594.8\)</span> and an F-value of that the <strong>sum of squared errors</strong> in the restricted model was approximately <strong>3.5 times larger</strong> than in the model that included the treatment groups: <em>Audio</em>, <em>Video</em>, and (implicitly) <em>Control</em>.</p>
<p>This suggests that the chance of all three group means being equal — and thus, their inclusion in the <em>full model</em> having no impact — is <strong>extremely small</strong>.</p>
<p>Still, in order to make a <strong>scientific claim</strong>, we need to test this assumption formally by stating and rejecting an (admittedly ridiculous) null hypothesis:</p>
<p><strong>Hypothesis 0:</strong> <span class="math display">\[Mean(Conv_{Control})=Mean(Conv_{Audio})=Mean(Conv_{Video})\]</span> If <strong>Hypothesis 0</strong> were true, then including the treatment variables in the model would <strong>not</strong> reduce the error. The full model would perform just as poorly as the restricted one — meaning the F-statistic should be around <strong>1</strong>. Thus, we can simplify our <strong>Hypothesis 0</strong> to:</p>
<p><strong>Hypothesis 0:</strong></p>
<p><span class="math display">\[F=1\]</span></p>
<blockquote class="blockquote">
<p>🤓 <strong>Only for the curious reader:</strong> You might wonder — should the F-value be 0 under <em>Hypothesis 0</em>? After all, if there is no improvement, the numerator of the F-value (i.e., <span class="math inline">\(SSE_{\text{restr}} - SSE_{\text{full}}\)</span>) in <a href="#eq-FValue" class="quarto-xref">Equation&nbsp;2</a> would be zero.</p>
<p>That intuition is partly correct: if <em>Hypothesis 0</em> is true, the <strong>expected value</strong> of this difference is indeed zero: <span class="math display">\[
E(SSE_{\text{restr}} - SSE_{\text{full}}) = 0
\]</span></p>
<p>However, the <strong>variance</strong> of <span class="math inline">\((SSE_{\text{restr}} - SSE_{\text{full}})\)</span> is <strong>not zero</strong>, because repeated sampling would yield slightly different SSEs for each model. In fact, <span class="math inline">\(SSE_{\text{restr}} - SSE_{\text{full}}\)</span> if <em>Hypothesis 0</em> is true: <span class="math display">\[Var(SSE_{restr}-SSE_{Full})=Var(SSE_{Full})\]</span></p>
<p>Since we find these two variances in the divident and divisor of <a href="#eq-FValueOrg" class="quarto-xref">Equation&nbsp;1</a>, <span class="math inline">\(F=1\)</span> — if the <em>Hypothesis 0</em> is true.</p>
</blockquote>
<p>Although we obtained an F-value of <span class="math inline">\(F = 594.8\)</span>, we cannot immediately rule out the possibility that this result was due to <strong>random chance</strong> — that is, a fluke in our sample — and that the true <em>F-value</em> might still be 1.</p>
<p><strong>However, we can assess how (un)likely it would be to obtain such a high <em>F-value</em> if <em>Hypothesis 0</em> were true.</strong></p>
<p>To do this, we calculate a <strong>p-value</strong>, which represents the probability of observing an <em>F-value</em> as extreme as the one we found — <strong>assuming Hypothesis 0 is true</strong>.</p>
<p>To compute the <em>p-value</em> from the <em>F-distribution</em>, we need to know the degrees of freedom for the two variances we compare according to <a href="#eq-FValue" class="quarto-xref">Equation&nbsp;2</a>. The first one is <span class="math inline">\(df_{restr}-df_{full}\)</span> (341-339=2) and the second one is <span class="math inline">\(df_{full}\)</span> (339).</p>
<p>Since we trying to reject the hypothesis with a sample <em>F-value</em> that is far to the right of <span class="math inline">\(F=1\)</span> we are performing a <em>right-tail</em> test. Below is the related code and the result:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>PValue<span class="ot">=</span><span class="fu">pf</span>(<span class="fl">594.8</span>, <span class="at">df1 =</span> <span class="dv">2</span>, <span class="at">df2 =</span> <span class="dv">339</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"The probability to get such an high F-Value, </span><span class="sc">\n</span><span class="st">if the Hyppothesis 0 were true,</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="st">is (in scientific notation):</span><span class="sc">\n</span><span class="st">"</span>, PValue)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>The probability to get such an high F-Value, 
if the Hyppothesis 0 were true,
is (in scientific notation):
 1.352198e-111</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"The probability to get such an high F-Value, </span><span class="sc">\n</span><span class="st">if the Hyppothesis 0 were true,</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="st">is (written out):</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">format</span>(PValue, <span class="at">scientific =</span> <span class="cn">FALSE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>The probability to get such an high F-Value, 
if the Hyppothesis 0 were true,
is (written out):
 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001352198</code></pre>
</div>
</div>
<p>With such a low probability for a <em>Type-1</em> error we can safely state:</p>
<p><strong>One of our treatments, did significantly influence the conversions</strong></p>
<p>To identify which treatment <em>Audio</em> or <em>Video</em> (or possibly both) influenced conversions, we need further testing, which exceeds the scope of this article.</p>
<p>Happy analytics!</p>
<!-- ## Within Between -->
<!-- ```{r} -->
<!-- #| code-fold: true -->
<!-- #| warning: false -->
<!-- #| message: false -->
<!-- ggplot(DataWeb, aes(x = Conversions, color = Treatment, fill = Treatment)) + -->
<!--   geom_density(alpha = 0.3) + -->
<!--   geom_vline(xintercept = MeansByTreatment[[1,2]], color = "red",linewidth=0.7) + -->
<!--   geom_vline(xintercept = MeansByTreatment[[2,2]], color = "green",linewidth=0.7) + -->
<!--   geom_vline(xintercept = MeansByTreatment[[3,2]], color = "blue",linewidth=0.7) + -->
<!--   geom_vline(xintercept = mean(DataWeb$Conversions), color = "black",linewidth=1)+ -->
<!--   labs(y = "") +              # Set y-axis title -->
<!--   scale_y_continuous(breaks = NULL)+ -->
<!-- annotate("text", x = MeansByTreatment[[1,2]], y = 0.1, -->
<!--   label = round(MeansByTreatment[[1,2]],2), color = "red", angle = 90, -->
<!--   vjust = -0.5, size = 3) + -->
<!--   annotate("text", x = MeansByTreatment[[2,2]], y = 0.1, -->
<!--     label = round(MeansByTreatment[[2,2]],2), color = "green", angle = 90, -->
<!--     vjust = -0.5, size = 3) + -->
<!--   annotate("text", x = MeansByTreatment[[3,2]], y = 0.1, -->
<!--     label = round(MeansByTreatment[[3,2]],2), color = "blue", angle = 90, -->
<!--     vjust = -0.5, size = 3) + -->
<!--   annotate("text", x = mean(DataWeb$Conversions), y = 0.1, -->
<!--     label = round(mean(DataWeb$Conversions),2), color = "black", angle = 90, -->
<!--     vjust = -0.5, size = 3) + -->
<!--   theme_minimal() -->
<!-- ``` -->
<!-- ## Anova -->
<!-- ```{r} -->
<!-- #| code-fold: true -->
<!-- #| warning: false -->
<!-- #| message: false -->
<!-- ggplot(DataWeb, aes(x = Conversions, color = Treatment, fill = Treatment)) + -->
<!--   geom_density(alpha = 0.3) + -->
<!--   geom_vline(xintercept = MeansByTreatment[[1,2]], color = "red",linewidth=0.7) + -->
<!--   geom_vline(xintercept = MeansByTreatment[[2,2]], color = "green",linewidth=0.7) + -->
<!--   geom_vline(xintercept = MeansByTreatment[[3,2]], color = "blue",linewidth=0.7) + -->
<!--   geom_vline(xintercept = mean(DataWeb$Conversions), color = "black",linewidth=1)+ -->
<!-- annotate("text", x = MeansByTreatment[[1,2]], y = 0.1, label = MeansByTreatment[[1,2]], color = "red", angle = 90, vjust = -0.5, size = 3) + -->
<!--   annotate("text", x = MeansByTreatment[[2,2]], y = 0.1, label = MeansByTreatment[[2,2]], color = "green", angle = 90, vjust = -0.5, size = 3) + -->
<!--   annotate("text", x = MeansByTreatment[[3,2]], y = 0.1, label = MeansByTreatment[[3,2]], color = "blue", angle = 90, vjust = -0.5, size = 3) + -->
<!--   annotate("text", x = mean(DataWeb$Conversions), y = 0.1, label = mean(DataWeb$Conversions), color = "black", angle = 90, vjust = -0.5, size = 3) + -->
<!--   theme_minimal() -->
<!-- ``` -->
<!-- ```{r} -->
<!-- #| code-fold: true -->
<!-- #| warning: false -->
<!-- #| message: false -->
<!-- # Conditional Means by Treatment -->
<!--  DataWeb %>% -->
<!--   group_by(Treatment) %>% -->
<!--   summarise(Mean = mean(Conversions), N=n()) -->
<!-- ``` -->
<!-- ```{r} -->
<!-- #| code-fold: true -->
<!-- #| warning: false -->
<!-- #| message: false -->
<!-- anova(ModelLM) -->
<!-- ``` -->
<!-- **Sum of Squares Between** -->
<!-- ```{r} -->
<!-- #| code-fold: true -->
<!-- #| warning: false -->
<!-- #| message: false -->
<!-- cat("Mean Control:",MeansByTreatment[[1,2]]) -->
<!-- cat("Mean Audio:",MeansByTreatment[[2,2]]) -->
<!-- cat("Mean Video:",MeansByTreatment[[3,2]]) -->
<!-- cat("Grand Mean: ", GrandMean) -->
<!-- SumOfSquaresTreat= -->
<!-- ((MeansByTreatment[[1,2]]-GrandMean)^2*151+ -->
<!--  (MeansByTreatment[[2,2]]-GrandMean)^2*68+ -->
<!--  (MeansByTreatment[[3,2]]-GrandMean)^2*123) -->
<!-- cat( "Sum of Squares Treatment", SumOfSquaresTreat) -->
<!-- ``` -->
<!-- **Sum of Squares Within** -->
<!-- ```{r} -->
<!-- #| code-fold: true -->
<!-- #| warning: false -->
<!-- #| message: false -->
<!-- SumOFSquaresWithin=0 -->
<!-- for (i in c(1:N)) -->
<!-- { -->
<!--   # For all "Control" records -->
<!--   if (DataWeb[i,"Treatment"][[1]]=="Control") -->
<!--   { -->
<!--     SumOFSquaresWithin=SumOFSquaresWithin+ -->
<!--        (DataWeb[i,"Conversions"][[1]]-MeansByTreatment[1,"Mean"][[1]])^2 -->
<!-- } -->
<!--   # For all "Audio" records -->
<!--   if (DataWeb[i,"Treatment"][[1]]=="Audio") -->
<!--   { -->
<!--     SumOFSquaresWithin=SumOFSquaresWithin+ -->
<!--        (DataWeb[i,"Conversions"][[1]]-MeansByTreatment[2,"Mean"][[1]])^2 -->
<!--   } -->
<!--   # For all "Video" records -->
<!--   if (DataWeb[i,"Treatment"][[1]]=="Video") -->
<!--   { -->
<!--     SumOFSquaresWithin=SumOFSquaresWithin+ -->
<!--        (DataWeb[i,"Conversions"][[1]]-MeansByTreatment[3,"Mean"][[1]])^2 -->
<!--   } -->
<!-- } -->
<!-- cat("Sum of Squares Within Groups:",SumOFSquaresWithin) -->
<!-- ``` -->
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>